name = "coki-oa-web"
account_id = "my-cloudflare-account-id"
main = "workers-site/index.js"
compatibility_date = "2022-02-03"

[site]
bucket = "out"

[env.develop]
route = "my-develop-domain/*"
vars = { ANALYTICS_ENABLED = false }

[env.staging]
route = "my-staging-domain/*"
vars = { ANALYTICS_ENABLED = false }

[env.production]
route = "my-production-domain/*"
vars = { ANALYTICS_ENABLED = true }