name = "coki-oa-web-api-v1"
main = "dist/index.mjs"
compatibility_date = "2022-02-03"

[build]
command = "yarn run build"

[site]
bucket = "./public"

[[ d1_databases ]]
binding = "DB"
database_name = "db"
database_id = "db"
