name = "coki-oa-web-api"
main = "dist/index.mjs"
compatibility_date = "2022-11-03"

[site]
bucket = "./public"

#[[rules]]
#type = "ESModule"
#globs = ["**/*.mjs"]

[build]
command = "yarn run build"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true

[[ d1_databases ]]
binding = "DB"
database_name = "db"
database_id = "db"
