name = "coki-oa-web-api-v1"
account_id = "my-cloudflare-account-id"
main = "dist/index.mjs"
compatibility_date = "2022-02-03"

[build]
command = "yarn run build"

[site]
bucket = "./public"

[env.develop]
route = "my-develop-domain/*"

[env.staging]
route = "my-staging-domain/*"

[env.production]
route = "my-production-domain/*"