name: "Setup Environment"
description: "Setup the COKI OA Web GitHub Actions environment"

inputs:
  bucket_name:
    description: "The COKI OA Web Google Cloud Storage bucket name"
    required: true
  wrangler:
    description: "Whether to install Wrangler or not"
    default: "false"
    required: false
  vercel:
    description: "Whether to install Vercel CLI or not"
    default: "false"
    required: false
  playwright:
    description: "Whether to install Playwright or not"
    default: "false"
    required: false
  gcp_credentials:
    description: "The GCP credentials JSON for accessing the Google Cloud Storage bucket"
    required: true
  dataset_version:
    description: "The COKI OA Web dataset version"
    required: false
    default: "v10"
  node_version:
    description: "The NodeJS version"
    required: true
    default: "16.16.0"
  yarn_version:
    description: "The Yarn version"
    required: false
    default: "3.3.1"
  vercel_version:
    description: "The Vercel CLI version"
    required: false
    default: "28.11.1"
  download_images:
    description: "Whether to download images or not"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install Vercel CLI
      if: inputs.vercel == 'true'
      run: npm install --global vercel@${{ inputs.vercel_version }}
      shell: bash

    - name: Install Yarn
      run: |
        corepack enable
        corepack prepare yarn@${{ inputs.yarn_version }} --activate
      shell: bash

    - name: Install project dependencies
      run: |
        yarn install
        yarn workspace coki-oa-web-api install
        yarn workspace coki-oa-images install
      shell: bash

    - name: Install Playwright
      if: inputs.playwright == 'true'
      run: |
        npx playwright install-deps
        npx playwright install
        npx playwright install msedge
      shell: bash

    - name: Setup Google Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Download and Extract Data
      run: |
        gsutil cp gs://${{ inputs.bucket_name }}/${{ inputs.dataset_version }}/data.zip data.zip
        ./data.sh
      shell: bash

    - name: Download and Extract Images
      if: inputs.download_images == 'true'
      run: |
        gsutil cp gs://${{ inputs.bucket_name }}/${{ inputs.dataset_version }}/images.zip images.zip
        gsutil cp gs://${{ inputs.bucket_name }}/${{ inputs.dataset_version }}/social-cards.zip social-cards.zip
        ./images.sh
      shell: bash