name: Build and Deploy

on:
  push:
    tags:
      - 'v*'
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment develop
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "ENVIRONMENT=develop" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_HOST=https://develop.open.coki.ac" >> $GITHUB_ENV

      - name: Set environment staging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_HOST=https://staging.open.coki.ac" >> $GITHUB_ENV

      - name: Set environment production
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_HOST=https://open.coki.ac" >> $GITHUB_ENV

      - name: Current Checked Out Ref
        run: |
          git symbolic-ref -q --short HEAD || git describe --tags --exact-match

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Wrangler
        run: |
          npm i "@cloudflare/wrangler@1.19.11" -g

      - name: Install Dependencies
        run: |
          yarn install
          cd ./workers-api && yarn install

      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download and Extract Data
        env:
          DATASET_VERSION: v2
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          gsutil cp gs://${BUCKET_NAME}/${DATASET_VERSION}/latest.zip latest.zip
          ./data.sh

      - name: Build and Export Web App
        env:
          DATA_PATH: ./latest/data
        run: |
          yarn build
          yarn export

      - name: Save wrangler.toml files
        env:
          WRANGLER_CONFIG: ${{ secrets.WRANGLER_CONFIG }}
          WRANGLER_CONFIG_API: ${{ secrets.WRANGLER_CONFIG_API }}
        run: |
          echo "${WRANGLER_CONFIG}" > wrangler.toml
          echo "${WRANGLER_CONFIG_API}" > ./workers-api/wrangler.toml

      - name: Publish Cloudflare Workers API
        working-directory: ./workers-api
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          wrangler publish -e ${ENVIRONMENT}

      - name: Publish Cloudflare Workers WebApp
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          wrangler publish -e ${ENVIRONMENT}
