# Build and deploy project from the develop and main branches and on new GitHub releases

name: "Build and Deploy"

on:
  push:
    tags:
      - 'v*'
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment develop
        if: github.ref == 'refs/heads/develop'
        run: echo "COKI_ENVIRONMENT=develop" >> $GITHUB_ENV

      - name: Set environment staging
        if: github.ref == 'refs/heads/main'
        run: echo "COKI_ENVIRONMENT=staging" >> $GITHUB_ENV

      - name: Set environment production
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "COKI_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Current Checked Out Ref
        run: git symbolic-ref -q --short HEAD || git describe --tags --exact-match

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          bucket_name: ${{ secrets.BUCKET_NAME }}
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          vercel: true

      - name: Build App
        uses: ./.github/actions/build-app
        with:
          environment: ${{ env.COKI_ENVIRONMENT }}
          plausible_api_token: ${{ secrets.PLAUSIBLE_API_TOKEN }}
          wrangler_config: ${{ secrets.WRANGLER_CONFIG_API }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
