name: e2e Tests

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: |
          sudo apt install xsel
          yarn install
          npx playwright install-deps
          npx playwright install
          npx playwright install msedge
          cd ./workers-api && yarn install

      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download and Extract Data
        env:
          DATASET_VERSION: v6
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          gsutil cp gs://${BUCKET_NAME}/${DATASET_VERSION}/latest.zip latest.zip
          ./data.sh

      - name: Run e2e Tests
        env:
          DATA_PATH: ./latest/data
        run: |
          yarn run test:e2e
