name: e2e Tests

on: push

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@3.3.1 --activate
          yarn install
          yarn workspace coki-oa-web-api install
          npx playwright install-deps
          npx playwright install
          npx playwright install msedge

      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download and Extract Data
        env:
          DATASET_VERSION: v8
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          gsutil cp gs://${BUCKET_NAME}/${DATASET_VERSION}/data.zip data.zip
          ./data.sh

      - name: Run e2e Tests
        run: |
          yarn run test:e2e