name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          yarn install

      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download and Extract Data
        env:
          DATASET_VERSION: v3
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          gsutil cp gs://${BUCKET_NAME}/${DATASET_VERSION}/latest.zip latest.zip
          ./data.sh

      - name: Run Unit Tests
        env:
          DATA_PATH: ./latest/data
        run: |
          yarn run test:jest