# Unit tests for COKI Open Access Dashboard web application

name: "Unit Tests"

on: push

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          bucket_name: ${{ secrets.BUCKET_NAME }}
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run Unit Tests
        working-directory: ./dashboard
        run: yarn run test:jest