# Unit tests for COKI Open Access Dashboard web application

name: "Unit Tests"

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          bucket_name: ${{ secrets.BUCKET_NAME }}
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Run Unit Tests
        working-directory: ./dashboard
        run: yarn run test:jest